"""empty message

Revision ID: 0a95859913f1
Revises: b73f5e4219e4
Create Date: 2021-07-14 17:35:18.282762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a95859913f1'
down_revision = 'b73f5e4219e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_note', sa.String(), nullable=True))
    op.drop_column('meeting', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('meeting', 'meeting_note')
    # ### end Alembic commands ###
