"""empty message

Revision ID: 760d2933d1ed
Revises: d2cb19236048
Create Date: 2021-07-11 10:17:14.016682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760d2933d1ed'
down_revision = 'd2cb19236048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_end', sa.Time(), nullable=True))
    op.add_column('meeting', sa.Column('meeting_start', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'meeting_start')
    op.drop_column('meeting', 'meeting_end')
    # ### end Alembic commands ###
