"""empty message

Revision ID: 98995bc7df2f
Revises: ed504d0f93c2
Create Date: 2021-07-10 16:52:00.810947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98995bc7df2f'
down_revision = 'ed504d0f93c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_access', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_access')
    # ### end Alembic commands ###
