"""empty message

Revision ID: b73f5e4219e4
Revises: a8d018d19f4d
Create Date: 2021-07-14 16:33:51.455362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73f5e4219e4'
down_revision = 'a8d018d19f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'meeting_date')
    # ### end Alembic commands ###
