"""empty message

Revision ID: dfc166a75b37
Revises: 182d99ae3656
Create Date: 2021-07-09 17:36:21.427764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc166a75b37'
down_revision = '182d99ae3656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'meeting_date')
    # ### end Alembic commands ###
