"""empty message

Revision ID: ed504d0f93c2
Revises: ac4fef5073e3
Create Date: 2021-07-10 12:19:43.084912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed504d0f93c2'
down_revision = 'ac4fef5073e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.drop_column('meeting', 'update_time')
    op.add_column('user', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_time')
    op.add_column('meeting', sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('meeting', 'updated_time')
    # ### end Alembic commands ###
